package idle.core;

import java.util.List;

/**
 * Catalogue des molécules, rangées par rayon ({@link Molecule.Kind}) : 430 molécules réelles, de
 * H₂ à la quinine. Le catalogue est volontairement large, pour pouvoir y trier ensuite.
 *
 * <p>Chaque molécule est décrite par sa formule en clair ({@link Molecule#of}), qui lui sert
 * aussi d'identifiant. Aucune ne contient d'élément unique (gaz nobles, actinides) : un élément
 * unique ne peut pas quitter le tableau périodique.
 *
 * <p>Ce qui borne le nombre de molécules d'une même sorte, c'est le prix : la première demande sa
 * formule une fois, la deuxième deux fois, la troisième quatre fois
 * ({@link Game#nextMoleculeCost(String)}), et un exemplaire de chaque élément doit rester dans le
 * tableau. Avec neuf exemplaires par élément, trois molécules d'eau (2, 4 puis 8 hydrogènes) et
 * aucune de glucose (12 hydrogènes) ; les Isotopes de l'arbre de matière noire (seize, puis
 * vingt-cinq exemplaires) ouvrent les molécules lourdes. Aucune formule ne demande plus de 24
 * atomes d'un même élément, ni plus de 15 d'un lanthanide : toutes sont donc faisables au moins
 * une fois, arbre complet.
 *
 * <p>Chaque molécule occupe aussi de l'espace, d'après son nombre de protons
 * ({@link Game#moleculeVolume(String)}).
 *
 * <p>Chaque molécule créée donne quelque chose ({@link Molecule.Bonus}), et peu : quelques pour
 * cent d'espace, de particules, d'atomes ou de croissance de la matière noire, ou un exemplaire de
 * plus au maximum d'un de ses éléments. Ces nombres sont un premier réglage, à trier.
 * <ul>
 *   <li>Les petites molécules ont été réglées une à une : 2 à 10 %, et quinze plafonds relevés,
 *       ceux des corps simples (H₂, O₂, N₂, F₂, Cl₂, Br₂, I₂, P₄, S₈) et de six hydrures (CH₄, SiH₄,
 *       AsH₃, B₂H₆, GeH₄, H₂Se).</li>
 *   <li>Dans les sept autres rayons, une molécule relève le plafond du métal le plus rare de sa
 *       formule (celui que le moins de molécules du catalogue contiennent), si aucune molécule
 *       placée avant elle dans son rayon ne l'a déjà pris : la soude pour le sodium, la galène
 *       pour le plomb, la chromite pour le chrome. Un métal a donc au plus une molécule par rayon,
 *       et 138 molécules relèvent un plafond.</li>
 *   <li>Les 251 autres augmentent une grandeur, à tour de rôle selon la dominante de leur rayon
 *       (les particules pour les acides et la chimie du carbone, les atomes pour les sels et les
 *       minéraux, l'espace pour les matériaux, la matière noire pour le vivant et les éléments
 *       rares). Le pourcentage grandit avec la taille de la molécule, de 4 % sous 30 protons à
 *       15 % au-delà de 260, plus un point par rayon : 4 % pour l'acide chlorhydrique, 20 % pour
 *       l'ATP.</li>
 * </ul>
 *
 * <p>Chaque molécule a aussi un état ({@link Molecule.State}), celui de sa substance à température
 * ambiante, qui décide du lieu où elle se rassemble ({@link Game#formSubstance(String)}) : 45 gaz,
 * 61 liquides, 85 solides faits de molécules entières (le sucre, l'aspirine), 227 cristaux (les
 * sels, les minéraux, les céramiques) et 12 métaux (les alliages, les carbures et nitrures
 * conducteurs, les aimants). Les états viennent de mémoire, et ceux des composés superlourds sont
 * ceux de leurs analogues plus légers : à vérifier avant de s'y fier.
 */
public final class Molecules {

    public static final List<Molecule> DEFAULT = List.of(
            // Les corps simples à plusieurs atomes et les petites molécules, souvent des gaz.
            Molecule.of(Molecule.Kind.SIMPLE, "Dihydrogène", "H2").uncapping("H").gas(),
            Molecule.of(Molecule.Kind.SIMPLE, "Dioxygène", "O2").uncapping("O").gas(),
            Molecule.of(Molecule.Kind.SIMPLE, "Diazote", "N2").uncapping("N").gas(),
            Molecule.of(Molecule.Kind.SIMPLE, "Ozone", "O3").boosting(Molecule.Stat.SPACE, 0.03).gas(),
            Molecule.of(Molecule.Kind.SIMPLE, "Difluor", "F2").uncapping("F").gas(),
            Molecule.of(Molecule.Kind.SIMPLE, "Dichlore", "Cl2").uncapping("Cl").gas(),
            Molecule.of(Molecule.Kind.SIMPLE, "Dibrome", "Br2").uncapping("Br").liquid(),
            Molecule.of(Molecule.Kind.SIMPLE, "Diiode", "I2").uncapping("I").solid(),
            Molecule.of(Molecule.Kind.SIMPLE, "Phosphore blanc", "P4").uncapping("P").solid(),
            Molecule.of(Molecule.Kind.SIMPLE, "Soufre", "S8").uncapping("S").solid(),
            Molecule.of(Molecule.Kind.SIMPLE, "Eau", "H2O").boosting(Molecule.Stat.PARTICLES, 0.05).liquid(),
            Molecule.of(Molecule.Kind.SIMPLE, "Eau oxygénée", "H2O2").boosting(Molecule.Stat.PARTICLES, 0.05).liquid(),
            Molecule.of(Molecule.Kind.SIMPLE, "Monoxyde de carbone", "CO").boosting(Molecule.Stat.ATOMS, 0.02).gas(),
            Molecule.of(Molecule.Kind.SIMPLE, "Dioxyde de carbone", "CO2").boosting(Molecule.Stat.SPACE, 0.05).gas(),
            Molecule.of(Molecule.Kind.SIMPLE, "Ammoniac", "NH3").boosting(Molecule.Stat.ATOMS, 0.03).gas(),
            Molecule.of(Molecule.Kind.SIMPLE, "Méthane", "CH4").uncapping("C").gas(),
            Molecule.of(Molecule.Kind.SIMPLE, "Monoxyde d'azote", "NO").boosting(Molecule.Stat.SPACE, 0.03).gas(),
            Molecule.of(Molecule.Kind.SIMPLE, "Dioxyde d'azote", "NO2").boosting(Molecule.Stat.SPACE, 0.03).gas(),
            Molecule.of(Molecule.Kind.SIMPLE, "Protoxyde d'azote", "N2O").boosting(Molecule.Stat.DARK_GROWTH, 0.05).gas(),
            Molecule.of(Molecule.Kind.SIMPLE, "Tétroxyde de diazote", "N2O4").boosting(Molecule.Stat.SPACE, 0.05).gas(),
            Molecule.of(Molecule.Kind.SIMPLE, "Dioxyde de soufre", "SO2").boosting(Molecule.Stat.PARTICLES, 0.05).gas(),
            Molecule.of(Molecule.Kind.SIMPLE, "Trioxyde de soufre", "SO3").boosting(Molecule.Stat.PARTICLES, 0.08).liquid(),
            Molecule.of(Molecule.Kind.SIMPLE, "Sulfure d'hydrogène", "H2S").boosting(Molecule.Stat.ATOMS, 0.02).gas(),
            Molecule.of(Molecule.Kind.SIMPLE, "Phosphine", "PH3").boosting(Molecule.Stat.DARK_GROWTH, 0.05).gas(),
            Molecule.of(Molecule.Kind.SIMPLE, "Silane", "SiH4").uncapping("Si").gas(),
            Molecule.of(Molecule.Kind.SIMPLE, "Hydrazine", "N2H4").boosting(Molecule.Stat.SPACE, 0.08).liquid(),
            Molecule.of(Molecule.Kind.SIMPLE, "Arsine", "AsH3").uncapping("As").gas(),
            Molecule.of(Molecule.Kind.SIMPLE, "Diborane", "B2H6").uncapping("B").gas(),
            Molecule.of(Molecule.Kind.SIMPLE, "Germane", "GeH4").uncapping("Ge").gas(),
            Molecule.of(Molecule.Kind.SIMPLE, "Séléniure d'hydrogène", "H2Se").uncapping("Se").gas(),
            Molecule.of(Molecule.Kind.SIMPLE, "Disulfure de carbone", "CS2").boosting(Molecule.Stat.PARTICLES, 0.05).liquid(),
            Molecule.of(Molecule.Kind.SIMPLE, "Cyanure d'hydrogène", "HCN").boosting(Molecule.Stat.DARK_GROWTH, 0.05).liquid(),
            Molecule.of(Molecule.Kind.SIMPLE, "Dioxyde de chlore", "ClO2").boosting(Molecule.Stat.ATOMS, 0.03).gas(),
            Molecule.of(Molecule.Kind.SIMPLE, "Monochlorure d'iode", "ICl").boosting(Molecule.Stat.ATOMS, 0.03).solid(),
            Molecule.of(Molecule.Kind.SIMPLE, "Trifluorure d'azote", "NF3").boosting(Molecule.Stat.SPACE, 0.05).gas(),
            Molecule.of(Molecule.Kind.SIMPLE, "Trifluorure de bore", "BF3").boosting(Molecule.Stat.DARK_GROWTH, 0.05).gas(),
            Molecule.of(Molecule.Kind.SIMPLE, "Tétrafluorure de silicium", "SiF4").boosting(Molecule.Stat.PARTICLES, 0.08).gas(),
            Molecule.of(Molecule.Kind.SIMPLE, "Hexafluorure de soufre", "SF6").boosting(Molecule.Stat.SPACE, 0.10).gas(),
            Molecule.of(Molecule.Kind.SIMPLE, "Trichlorure de phosphore", "PCl3").boosting(Molecule.Stat.ATOMS, 0.03).liquid(),
            Molecule.of(Molecule.Kind.SIMPLE, "Pentachlorure de phosphore", "PCl5").boosting(Molecule.Stat.ATOMS, 0.05).solid(),
            Molecule.of(Molecule.Kind.SIMPLE, "Pentoxyde de phosphore", "P4O10").boosting(Molecule.Stat.PARTICLES, 0.10).solid(),

            // Les acides, minéraux puis organiques, et les bases.
            Molecule.of(Molecule.Kind.ACID, "Acide chlorhydrique", "HCl").boosting(Molecule.Stat.PARTICLES, 0.04).gas(),
            Molecule.of(Molecule.Kind.ACID, "Acide fluorhydrique", "HF").boosting(Molecule.Stat.ATOMS, 0.04).gas(),
            Molecule.of(Molecule.Kind.ACID, "Acide bromhydrique", "HBr").boosting(Molecule.Stat.PARTICLES, 0.06).gas(),
            Molecule.of(Molecule.Kind.ACID, "Acide iodhydrique", "HI").boosting(Molecule.Stat.SPACE, 0.06).gas(),
            Molecule.of(Molecule.Kind.ACID, "Acide sulfurique", "H2SO4").boosting(Molecule.Stat.PARTICLES, 0.06).liquid(),
            Molecule.of(Molecule.Kind.ACID, "Acide sulfureux", "H2SO3").boosting(Molecule.Stat.ATOMS, 0.06).liquid(),
            Molecule.of(Molecule.Kind.ACID, "Acide nitrique", "HNO3").boosting(Molecule.Stat.PARTICLES, 0.06).liquid(),
            Molecule.of(Molecule.Kind.ACID, "Acide nitreux", "HNO2").boosting(Molecule.Stat.SPACE, 0.04).liquid(),
            Molecule.of(Molecule.Kind.ACID, "Acide phosphorique", "H3PO4").boosting(Molecule.Stat.PARTICLES, 0.06).solid(),
            Molecule.of(Molecule.Kind.ACID, "Acide carbonique", "H2CO3").boosting(Molecule.Stat.ATOMS, 0.06).liquid(),
            Molecule.of(Molecule.Kind.ACID, "Acide borique", "H3BO3").uncapping("B").solid(),
            Molecule.of(Molecule.Kind.ACID, "Acide hypochloreux", "HClO").boosting(Molecule.Stat.PARTICLES, 0.04).liquid(),
            Molecule.of(Molecule.Kind.ACID, "Acide perchlorique", "HClO4").boosting(Molecule.Stat.SPACE, 0.06).liquid(),
            Molecule.of(Molecule.Kind.ACID, "Acide formique", "HCOOH").boosting(Molecule.Stat.PARTICLES, 0.04).liquid(),
            Molecule.of(Molecule.Kind.ACID, "Acide acétique", "CH3COOH").boosting(Molecule.Stat.ATOMS, 0.06).liquid(),
            Molecule.of(Molecule.Kind.ACID, "Acide oxalique", "C2H2O4").boosting(Molecule.Stat.PARTICLES, 0.06).solid(),
            Molecule.of(Molecule.Kind.ACID, "Acide lactique", "C3H6O3").boosting(Molecule.Stat.SPACE, 0.06).liquid(),
            Molecule.of(Molecule.Kind.ACID, "Acide citrique", "C6H8O7").boosting(Molecule.Stat.PARTICLES, 0.10).solid(),
            Molecule.of(Molecule.Kind.ACID, "Acide benzoïque", "C7H6O2").boosting(Molecule.Stat.ATOMS, 0.08).solid(),
            Molecule.of(Molecule.Kind.ACID, "Acide salicylique", "C7H6O3").boosting(Molecule.Stat.PARTICLES, 0.08).solid(),
            Molecule.of(Molecule.Kind.ACID, "Soude", "NaOH").uncapping("Na").crystal(),
            Molecule.of(Molecule.Kind.ACID, "Potasse", "KOH").uncapping("K").crystal(),
            Molecule.of(Molecule.Kind.ACID, "Lithine", "LiOH").uncapping("Li").crystal(),
            Molecule.of(Molecule.Kind.ACID, "Chaux éteinte", "Ca(OH)2").uncapping("Ca").crystal(),
            Molecule.of(Molecule.Kind.ACID, "Hydroxyde de magnésium", "Mg(OH)2").uncapping("Mg").crystal(),
            Molecule.of(Molecule.Kind.ACID, "Hydroxyde de baryum", "Ba(OH)2").uncapping("Ba").crystal(),
            Molecule.of(Molecule.Kind.ACID, "Hydroxyde d'aluminium", "Al(OH)3").uncapping("Al").crystal(),

            // Les sels : halogénures, carbonates, nitrates, sulfates, puis ceux des métaux de transition.
            Molecule.of(Molecule.Kind.SALT, "Sel de table", "NaCl").uncapping("Na").crystal(),
            Molecule.of(Molecule.Kind.SALT, "Chlorure de potassium", "KCl").uncapping("K").crystal(),
            Molecule.of(Molecule.Kind.SALT, "Chlorure de lithium", "LiCl").uncapping("Li").crystal(),
            Molecule.of(Molecule.Kind.SALT, "Chlorure de rubidium", "RbCl").uncapping("Rb").crystal(),
            Molecule.of(Molecule.Kind.SALT, "Chlorure de césium", "CsCl").uncapping("Cs").crystal(),
            Molecule.of(Molecule.Kind.SALT, "Chlorure de calcium", "CaCl2").uncapping("Ca").crystal(),
            Molecule.of(Molecule.Kind.SALT, "Chlorure de magnésium", "MgCl2").uncapping("Mg").crystal(),
            Molecule.of(Molecule.Kind.SALT, "Chlorure de strontium", "SrCl2").uncapping("Sr").crystal(),
            Molecule.of(Molecule.Kind.SALT, "Chlorure de baryum", "BaCl2").uncapping("Ba").crystal(),
            Molecule.of(Molecule.Kind.SALT, "Chlorure d'ammonium", "NH4Cl").boosting(Molecule.Stat.ATOMS, 0.05).crystal(),
            Molecule.of(Molecule.Kind.SALT, "Fluorure de sodium", "NaF").boosting(Molecule.Stat.PARTICLES, 0.05).crystal(),
            Molecule.of(Molecule.Kind.SALT, "Fluorure de lithium", "LiF").boosting(Molecule.Stat.SPACE, 0.05).crystal(),
            Molecule.of(Molecule.Kind.SALT, "Bromure de sodium", "NaBr").boosting(Molecule.Stat.ATOMS, 0.07).crystal(),
            Molecule.of(Molecule.Kind.SALT, "Bromure de potassium", "KBr").boosting(Molecule.Stat.DARK_GROWTH, 0.07).crystal(),
            Molecule.of(Molecule.Kind.SALT, "Iodure de sodium", "NaI").boosting(Molecule.Stat.ATOMS, 0.09).crystal(),
            Molecule.of(Molecule.Kind.SALT, "Iodure de potassium", "KI").boosting(Molecule.Stat.PARTICLES, 0.09).crystal(),
            Molecule.of(Molecule.Kind.SALT, "Iodure de césium", "CsI").boosting(Molecule.Stat.SPACE, 0.11).crystal(),
            Molecule.of(Molecule.Kind.SALT, "Chlorure d'argent", "AgCl").uncapping("Ag").crystal(),
            Molecule.of(Molecule.Kind.SALT, "Bromure d'argent", "AgBr").boosting(Molecule.Stat.ATOMS, 0.09).crystal(),
            Molecule.of(Molecule.Kind.SALT, "Iodure d'argent", "AgI").boosting(Molecule.Stat.DARK_GROWTH, 0.11).crystal(),
            Molecule.of(Molecule.Kind.SALT, "Iodure de plomb", "PbI2").uncapping("Pb").crystal(),
            Molecule.of(Molecule.Kind.SALT, "Bicarbonate de soude", "NaHCO3").boosting(Molecule.Stat.ATOMS, 0.07).crystal(),
            Molecule.of(Molecule.Kind.SALT, "Carbonate de sodium", "Na2CO3").boosting(Molecule.Stat.PARTICLES, 0.07).crystal(),
            Molecule.of(Molecule.Kind.SALT, "Carbonate de potassium", "K2CO3").boosting(Molecule.Stat.SPACE, 0.09).crystal(),
            Molecule.of(Molecule.Kind.SALT, "Carbonate de lithium", "Li2CO3").boosting(Molecule.Stat.ATOMS, 0.07).crystal(),
            Molecule.of(Molecule.Kind.SALT, "Salpêtre", "KNO3").boosting(Molecule.Stat.DARK_GROWTH, 0.07).crystal(),
            Molecule.of(Molecule.Kind.SALT, "Nitrate de sodium", "NaNO3").boosting(Molecule.Stat.ATOMS, 0.07).crystal(),
            Molecule.of(Molecule.Kind.SALT, "Nitrate d'ammonium", "NH4NO3").boosting(Molecule.Stat.PARTICLES, 0.07).crystal(),
            Molecule.of(Molecule.Kind.SALT, "Nitrate d'argent", "AgNO3").boosting(Molecule.Stat.SPACE, 0.09).crystal(),
            Molecule.of(Molecule.Kind.SALT, "Sulfate de sodium", "Na2SO4").boosting(Molecule.Stat.ATOMS, 0.09).crystal(),
            Molecule.of(Molecule.Kind.SALT, "Sulfate de magnésium", "MgSO4").boosting(Molecule.Stat.DARK_GROWTH, 0.09).crystal(),
            Molecule.of(Molecule.Kind.SALT, "Sulfate de cuivre", "CuSO4").uncapping("Cu").crystal(),
            Molecule.of(Molecule.Kind.SALT, "Sulfate de zinc", "ZnSO4").uncapping("Zn").crystal(),
            Molecule.of(Molecule.Kind.SALT, "Sulfate de fer", "FeSO4").uncapping("Fe").crystal(),
            Molecule.of(Molecule.Kind.SALT, "Sulfate de nickel", "NiSO4").uncapping("Ni").crystal(),
            Molecule.of(Molecule.Kind.SALT, "Sulfate d'ammonium", "(NH4)2SO4").boosting(Molecule.Stat.ATOMS, 0.09).crystal(),
            Molecule.of(Molecule.Kind.SALT, "Sulfate de thallium", "Tl2SO4").uncapping("Tl").crystal(),
            Molecule.of(Molecule.Kind.SALT, "Eau de Javel", "NaClO").boosting(Molecule.Stat.PARTICLES, 0.07).liquid(),
            Molecule.of(Molecule.Kind.SALT, "Chlorate de potassium", "KClO3").boosting(Molecule.Stat.SPACE, 0.09).crystal(),
            Molecule.of(Molecule.Kind.SALT, "Permanganate de potassium", "KMnO4").uncapping("Mn").crystal(),
            Molecule.of(Molecule.Kind.SALT, "Dichromate de potassium", "K2Cr2O7").uncapping("Cr").crystal(),
            Molecule.of(Molecule.Kind.SALT, "Cyanure de potassium", "KCN").boosting(Molecule.Stat.ATOMS, 0.07).crystal(),
            Molecule.of(Molecule.Kind.SALT, "Thiosulfate de sodium", "Na2S2O3").boosting(Molecule.Stat.DARK_GROWTH, 0.09).crystal(),
            Molecule.of(Molecule.Kind.SALT, "Sulfure de sodium", "Na2S").boosting(Molecule.Stat.ATOMS, 0.07).crystal(),
            Molecule.of(Molecule.Kind.SALT, "Peroxyde de sodium", "Na2O2").boosting(Molecule.Stat.PARTICLES, 0.07).crystal(),
            Molecule.of(Molecule.Kind.SALT, "Phosphate de sodium", "Na3PO4").boosting(Molecule.Stat.SPACE, 0.09).crystal(),
            Molecule.of(Molecule.Kind.SALT, "Phosphate de calcium", "Ca3(PO4)2").boosting(Molecule.Stat.ATOMS, 0.11).crystal(),
            Molecule.of(Molecule.Kind.SALT, "Acétate de sodium", "CH3COONa").boosting(Molecule.Stat.DARK_GROWTH, 0.07).crystal(),
            Molecule.of(Molecule.Kind.SALT, "Chlorure de fer", "FeCl3").boosting(Molecule.Stat.ATOMS, 0.09).crystal(),
            Molecule.of(Molecule.Kind.SALT, "Chlorure de cuivre", "CuCl2").boosting(Molecule.Stat.PARTICLES, 0.09).crystal(),
            Molecule.of(Molecule.Kind.SALT, "Chlorure d'aluminium", "AlCl3").uncapping("Al").crystal(),
            Molecule.of(Molecule.Kind.SALT, "Chlorure de cobalt", "CoCl2").uncapping("Co").crystal(),
            Molecule.of(Molecule.Kind.SALT, "Chlorure de zinc", "ZnCl2").boosting(Molecule.Stat.SPACE, 0.09).crystal(),
            Molecule.of(Molecule.Kind.SALT, "Chlorure d'étain", "SnCl2").uncapping("Sn").crystal(),
            Molecule.of(Molecule.Kind.SALT, "Fluorure d'étain", "SnF2").boosting(Molecule.Stat.ATOMS, 0.09).crystal(),
            Molecule.of(Molecule.Kind.SALT, "Chlorure d'or", "AuCl3").uncapping("Au").crystal(),
            Molecule.of(Molecule.Kind.SALT, "Chlorure de palladium", "PdCl2").uncapping("Pd").crystal(),
            Molecule.of(Molecule.Kind.SALT, "Chlorure de rhodium", "RhCl3").uncapping("Rh").crystal(),
            Molecule.of(Molecule.Kind.SALT, "Calomel", "Hg2Cl2").uncapping("Hg").crystal(),
            Molecule.of(Molecule.Kind.SALT, "Alun", "KAl(SO4)2").boosting(Molecule.Stat.DARK_GROWTH, 0.11).crystal(),
            Molecule.of(Molecule.Kind.SALT, "Borax", "Na2B4O7").uncapping("B").crystal(),

            // Les minéraux, par famille : oxydes, sulfures, carbonates, sulfates, phosphates, silicates.
            Molecule.of(Molecule.Kind.MINERAL, "Quartz", "SiO2").uncapping("Si").crystal(),
            Molecule.of(Molecule.Kind.MINERAL, "Corindon", "Al2O3").uncapping("Al").crystal(),
            Molecule.of(Molecule.Kind.MINERAL, "Hématite", "Fe2O3").uncapping("Fe").crystal(),
            Molecule.of(Molecule.Kind.MINERAL, "Magnétite", "Fe3O4").boosting(Molecule.Stat.ATOMS, 0.12).crystal(),
            Molecule.of(Molecule.Kind.MINERAL, "Goethite", "FeO(OH)").boosting(Molecule.Stat.SPACE, 0.08).crystal(),
            Molecule.of(Molecule.Kind.MINERAL, "Diaspore", "AlO(OH)").boosting(Molecule.Stat.PARTICLES, 0.08).crystal(),
            Molecule.of(Molecule.Kind.MINERAL, "Pyrite", "FeS2").boosting(Molecule.Stat.ATOMS, 0.08).crystal(),
            Molecule.of(Molecule.Kind.MINERAL, "Galène", "PbS").uncapping("Pb").crystal(),
            Molecule.of(Molecule.Kind.MINERAL, "Cinabre", "HgS").uncapping("Hg").crystal(),
            Molecule.of(Molecule.Kind.MINERAL, "Blende", "ZnS").uncapping("Zn").crystal(),
            Molecule.of(Molecule.Kind.MINERAL, "Covelline", "CuS").uncapping("Cu").crystal(),
            Molecule.of(Molecule.Kind.MINERAL, "Chalcocite", "Cu2S").boosting(Molecule.Stat.DARK_GROWTH, 0.10).crystal(),
            Molecule.of(Molecule.Kind.MINERAL, "Chalcopyrite", "CuFeS2").boosting(Molecule.Stat.ATOMS, 0.10).crystal(),
            Molecule.of(Molecule.Kind.MINERAL, "Argentite", "Ag2S").uncapping("Ag").crystal(),
            Molecule.of(Molecule.Kind.MINERAL, "Greenockite", "CdS").uncapping("Cd").crystal(),
            Molecule.of(Molecule.Kind.MINERAL, "Stibine", "Sb2S3").uncapping("Sb").crystal(),
            Molecule.of(Molecule.Kind.MINERAL, "Orpiment", "As2S3").uncapping("As").crystal(),
            Molecule.of(Molecule.Kind.MINERAL, "Réalgar", "As4S4").boosting(Molecule.Stat.SPACE, 0.14).crystal(),
            Molecule.of(Molecule.Kind.MINERAL, "Bismuthinite", "Bi2S3").uncapping("Bi").crystal(),
            Molecule.of(Molecule.Kind.MINERAL, "Molybdénite", "MoS2").uncapping("Mo").crystal(),
            Molecule.of(Molecule.Kind.MINERAL, "Cobaltite", "CoAsS").uncapping("Co").crystal(),
            Molecule.of(Molecule.Kind.MINERAL, "Arsénopyrite", "FeAsS").boosting(Molecule.Stat.PARTICLES, 0.10).crystal(),
            Molecule.of(Molecule.Kind.MINERAL, "Nickéline", "NiAs").uncapping("Ni").crystal(),
            Molecule.of(Molecule.Kind.MINERAL, "Kestérite", "Cu2ZnSnS4").uncapping("Sn").crystal(),
            Molecule.of(Molecule.Kind.MINERAL, "Calcite", "CaCO3").uncapping("Ca").crystal(),
            Molecule.of(Molecule.Kind.MINERAL, "Dolomite", "CaMg(CO3)2").uncapping("Mg").crystal(),
            Molecule.of(Molecule.Kind.MINERAL, "Magnésite", "MgCO3").boosting(Molecule.Stat.ATOMS, 0.08).crystal(),
            Molecule.of(Molecule.Kind.MINERAL, "Sidérite", "FeCO3").boosting(Molecule.Stat.DARK_GROWTH, 0.08).crystal(),
            Molecule.of(Molecule.Kind.MINERAL, "Rhodochrosite", "MnCO3").uncapping("Mn").crystal(),
            Molecule.of(Molecule.Kind.MINERAL, "Smithsonite", "ZnCO3").boosting(Molecule.Stat.ATOMS, 0.10).crystal(),
            Molecule.of(Molecule.Kind.MINERAL, "Cérusite", "PbCO3").boosting(Molecule.Stat.SPACE, 0.12).crystal(),
            Molecule.of(Molecule.Kind.MINERAL, "Strontianite", "SrCO3").uncapping("Sr").crystal(),
            Molecule.of(Molecule.Kind.MINERAL, "Withérite", "BaCO3").uncapping("Ba").crystal(),
            Molecule.of(Molecule.Kind.MINERAL, "Malachite", "Cu2CO3(OH)2").boosting(Molecule.Stat.PARTICLES, 0.12).crystal(),
            Molecule.of(Molecule.Kind.MINERAL, "Azurite", "Cu3(CO3)2(OH)2").boosting(Molecule.Stat.ATOMS, 0.14).crystal(),
            Molecule.of(Molecule.Kind.MINERAL, "Anhydrite", "CaSO4").boosting(Molecule.Stat.DARK_GROWTH, 0.10).crystal(),
            Molecule.of(Molecule.Kind.MINERAL, "Barytine", "BaSO4").boosting(Molecule.Stat.ATOMS, 0.12).crystal(),
            Molecule.of(Molecule.Kind.MINERAL, "Célestine", "SrSO4").boosting(Molecule.Stat.SPACE, 0.10).crystal(),
            Molecule.of(Molecule.Kind.MINERAL, "Anglésite", "PbSO4").boosting(Molecule.Stat.PARTICLES, 0.12).crystal(),
            Molecule.of(Molecule.Kind.MINERAL, "Fluorine", "CaF2").boosting(Molecule.Stat.ATOMS, 0.08).crystal(),
            Molecule.of(Molecule.Kind.MINERAL, "Cryolithe", "Na3AlF6").uncapping("Na").crystal(),
            Molecule.of(Molecule.Kind.MINERAL, "Apatite", "Ca5(PO4)3F").boosting(Molecule.Stat.DARK_GROWTH, 0.14).crystal(),
            Molecule.of(Molecule.Kind.MINERAL, "Hydroxyapatite", "Ca5(PO4)3OH").boosting(Molecule.Stat.ATOMS, 0.14).crystal(),
            Molecule.of(Molecule.Kind.MINERAL, "Pyromorphite", "Pb5(PO4)3Cl").boosting(Molecule.Stat.SPACE, 0.17).crystal(),
            Molecule.of(Molecule.Kind.MINERAL, "Vanadinite", "Pb5(VO4)3Cl").uncapping("V").crystal(),
            Molecule.of(Molecule.Kind.MINERAL, "Xénotime", "YPO4").uncapping("Y").crystal(),
            Molecule.of(Molecule.Kind.MINERAL, "Chaux vive", "CaO").boosting(Molecule.Stat.PARTICLES, 0.06).crystal(),
            Molecule.of(Molecule.Kind.MINERAL, "Périclase", "MgO").boosting(Molecule.Stat.ATOMS, 0.06).crystal(),
            Molecule.of(Molecule.Kind.MINERAL, "Bromellite", "BeO").uncapping("Be").crystal(),
            Molecule.of(Molecule.Kind.MINERAL, "Rutile", "TiO2").uncapping("Ti").crystal(),
            Molecule.of(Molecule.Kind.MINERAL, "Cassitérite", "SnO2").boosting(Molecule.Stat.DARK_GROWTH, 0.10).crystal(),
            Molecule.of(Molecule.Kind.MINERAL, "Cuprite", "Cu2O").boosting(Molecule.Stat.ATOMS, 0.10).crystal(),
            Molecule.of(Molecule.Kind.MINERAL, "Ténorite", "CuO").boosting(Molecule.Stat.SPACE, 0.08).crystal(),
            Molecule.of(Molecule.Kind.MINERAL, "Zincite", "ZnO").boosting(Molecule.Stat.PARTICLES, 0.08).crystal(),
            Molecule.of(Molecule.Kind.MINERAL, "Pyrolusite", "MnO2").boosting(Molecule.Stat.ATOMS, 0.08).crystal(),
            Molecule.of(Molecule.Kind.MINERAL, "Litharge", "PbO").boosting(Molecule.Stat.DARK_GROWTH, 0.10).crystal(),
            Molecule.of(Molecule.Kind.MINERAL, "Minium", "Pb3O4").boosting(Molecule.Stat.ATOMS, 0.17).crystal(),
            Molecule.of(Molecule.Kind.MINERAL, "Bismite", "Bi2O3").boosting(Molecule.Stat.SPACE, 0.14).crystal(),
            Molecule.of(Molecule.Kind.MINERAL, "Ilménite", "FeTiO3").boosting(Molecule.Stat.PARTICLES, 0.10).crystal(),
            Molecule.of(Molecule.Kind.MINERAL, "Pérovskite", "CaTiO3").boosting(Molecule.Stat.ATOMS, 0.10).crystal(),
            Molecule.of(Molecule.Kind.MINERAL, "Chromite", "FeCr2O4").uncapping("Cr").crystal(),
            Molecule.of(Molecule.Kind.MINERAL, "Spinelle", "MgAl2O4").boosting(Molecule.Stat.DARK_GROWTH, 0.10).crystal(),
            Molecule.of(Molecule.Kind.MINERAL, "Scheelite", "CaWO4").uncapping("W").crystal(),
            Molecule.of(Molecule.Kind.MINERAL, "Ferbérite", "FeWO4").boosting(Molecule.Stat.ATOMS, 0.12).crystal(),
            Molecule.of(Molecule.Kind.MINERAL, "Wulfénite", "PbMoO4").boosting(Molecule.Stat.SPACE, 0.12).crystal(),
            Molecule.of(Molecule.Kind.MINERAL, "Crocoïte", "PbCrO4").boosting(Molecule.Stat.PARTICLES, 0.12).crystal(),
            Molecule.of(Molecule.Kind.MINERAL, "Tantalite", "FeTa2O6").uncapping("Ta").crystal(),
            Molecule.of(Molecule.Kind.MINERAL, "Colombite", "FeNb2O6").uncapping("Nb").crystal(),
            Molecule.of(Molecule.Kind.MINERAL, "Zircon", "ZrSiO4").uncapping("Zr").crystal(),
            Molecule.of(Molecule.Kind.MINERAL, "Olivine", "Mg2SiO4").boosting(Molecule.Stat.ATOMS, 0.10).crystal(),
            Molecule.of(Molecule.Kind.MINERAL, "Enstatite", "MgSiO3").boosting(Molecule.Stat.DARK_GROWTH, 0.08).crystal(),
            Molecule.of(Molecule.Kind.MINERAL, "Wollastonite", "CaSiO3").boosting(Molecule.Stat.ATOMS, 0.08).crystal(),
            Molecule.of(Molecule.Kind.MINERAL, "Orthose", "KAlSi3O8").uncapping("K").crystal(),
            Molecule.of(Molecule.Kind.MINERAL, "Albite", "NaAlSi3O8").boosting(Molecule.Stat.SPACE, 0.12).crystal(),
            Molecule.of(Molecule.Kind.MINERAL, "Anorthite", "CaAl2Si2O8").boosting(Molecule.Stat.PARTICLES, 0.12).crystal(),
            Molecule.of(Molecule.Kind.MINERAL, "Talc", "Mg3Si4O10(OH)2").boosting(Molecule.Stat.ATOMS, 0.14).crystal(),
            Molecule.of(Molecule.Kind.MINERAL, "Kaolinite", "Al2Si2O5(OH)4").boosting(Molecule.Stat.DARK_GROWTH, 0.12).crystal(),
            Molecule.of(Molecule.Kind.MINERAL, "Topaze", "Al2SiO4F2").boosting(Molecule.Stat.ATOMS, 0.10).crystal(),
            Molecule.of(Molecule.Kind.MINERAL, "Grenat pyrope", "Mg3Al2Si3O12").boosting(Molecule.Stat.SPACE, 0.14).crystal(),
            Molecule.of(Molecule.Kind.MINERAL, "Béryl", "Be3Al2Si6O18").boosting(Molecule.Stat.PARTICLES, 0.17).crystal(),

            // Les matériaux fabriqués : céramiques, semi-conducteurs, piles, aimants, catalyseurs, complexes de métaux.
            Molecule.of(Molecule.Kind.MATERIAL, "Carbure de silicium", "SiC").uncapping("Si").crystal(),
            Molecule.of(Molecule.Kind.MATERIAL, "Carbure de calcium", "CaC2").uncapping("Ca").crystal(),
            Molecule.of(Molecule.Kind.MATERIAL, "Carbure de tungstène", "WC").uncapping("W").metal(),
            Molecule.of(Molecule.Kind.MATERIAL, "Carbure de titane", "TiC").uncapping("Ti").metal(),
            Molecule.of(Molecule.Kind.MATERIAL, "Carbure de bore", "B4C").uncapping("B").crystal(),
            Molecule.of(Molecule.Kind.MATERIAL, "Carbure de tantale et d'hafnium", "Ta4HfC5").uncapping("Hf").metal(),
            Molecule.of(Molecule.Kind.MATERIAL, "Nitrure de bore", "BN").boosting(Molecule.Stat.SPACE, 0.07).crystal(),
            Molecule.of(Molecule.Kind.MATERIAL, "Nitrure de titane", "TiN").boosting(Molecule.Stat.ATOMS, 0.07).metal(),
            Molecule.of(Molecule.Kind.MATERIAL, "Nitrure d'aluminium", "AlN").uncapping("Al").crystal(),
            Molecule.of(Molecule.Kind.MATERIAL, "Nitrure de gallium", "GaN").uncapping("Ga").crystal(),
            Molecule.of(Molecule.Kind.MATERIAL, "Nitrure de silicium", "Si3N4").boosting(Molecule.Stat.PARTICLES, 0.11).crystal(),
            Molecule.of(Molecule.Kind.MATERIAL, "Arséniure de gallium", "GaAs").uncapping("As").crystal(),
            Molecule.of(Molecule.Kind.MATERIAL, "Phosphure de gallium", "GaP").boosting(Molecule.Stat.DARK_GROWTH, 0.09).crystal(),
            Molecule.of(Molecule.Kind.MATERIAL, "Phosphure d'indium", "InP").uncapping("In").crystal(),
            Molecule.of(Molecule.Kind.MATERIAL, "Phosphure de bore", "BP").boosting(Molecule.Stat.SPACE, 0.07).crystal(),
            Molecule.of(Molecule.Kind.MATERIAL, "Antimoniure d'indium", "InSb").uncapping("Sb").crystal(),
            Molecule.of(Molecule.Kind.MATERIAL, "Tellurure de cadmium", "CdTe").uncapping("Cd").crystal(),
            Molecule.of(Molecule.Kind.MATERIAL, "Séléniure de cadmium", "CdSe").boosting(Molecule.Stat.ATOMS, 0.11).crystal(),
            Molecule.of(Molecule.Kind.MATERIAL, "Séléniure de zinc", "ZnSe").uncapping("Zn").crystal(),
            Molecule.of(Molecule.Kind.MATERIAL, "Séléniure de plomb", "PbSe").uncapping("Pb").crystal(),
            Molecule.of(Molecule.Kind.MATERIAL, "Tellurure de plomb", "PbTe").uncapping("Te").crystal(),
            Molecule.of(Molecule.Kind.MATERIAL, "Tellurure de bismuth", "Bi2Te3").uncapping("Bi").crystal(),
            Molecule.of(Molecule.Kind.MATERIAL, "Séléniure de cuivre et d'indium", "CuInSe2").uncapping("Cu").crystal(),
            Molecule.of(Molecule.Kind.MATERIAL, "Pérovskite solaire", "CH3NH3PbI3").boosting(Molecule.Stat.PARTICLES, 0.18).crystal(),
            Molecule.of(Molecule.Kind.MATERIAL, "Oxyde d'indium", "In2O3").boosting(Molecule.Stat.DARK_GROWTH, 0.13).crystal(),
            Molecule.of(Molecule.Kind.MATERIAL, "Oxyde de gallium", "Ga2O3").boosting(Molecule.Stat.SPACE, 0.11).crystal(),
            Molecule.of(Molecule.Kind.MATERIAL, "Dioxyde de germanium", "GeO2").uncapping("Ge").crystal(),
            Molecule.of(Molecule.Kind.MATERIAL, "Dioxyde de sélénium", "SeO2").boosting(Molecule.Stat.ATOMS, 0.09).solid(),
            Molecule.of(Molecule.Kind.MATERIAL, "Dioxyde de tellure", "TeO2").boosting(Molecule.Stat.PARTICLES, 0.11).crystal(),
            Molecule.of(Molecule.Kind.MATERIAL, "Titanate de baryum", "BaTiO3").uncapping("Ba").crystal(),
            Molecule.of(Molecule.Kind.MATERIAL, "Titanate de strontium", "SrTiO3").uncapping("Sr").crystal(),
            Molecule.of(Molecule.Kind.MATERIAL, "Titanate de plomb", "PbTiO3").boosting(Molecule.Stat.DARK_GROWTH, 0.13).crystal(),
            Molecule.of(Molecule.Kind.MATERIAL, "Niobate de lithium", "LiNbO3").uncapping("Nb").crystal(),
            Molecule.of(Molecule.Kind.MATERIAL, "Tantalate de lithium", "LiTaO3").uncapping("Ta").crystal(),
            Molecule.of(Molecule.Kind.MATERIAL, "Oxyde de lithium et de cobalt", "LiCoO2").uncapping("Co").crystal(),
            Molecule.of(Molecule.Kind.MATERIAL, "Phosphate de fer lithié", "LiFePO4").uncapping("Li").crystal(),
            Molecule.of(Molecule.Kind.MATERIAL, "Hydrure de lithium", "LiH").boosting(Molecule.Stat.SPACE, 0.07).crystal(),
            Molecule.of(Molecule.Kind.MATERIAL, "Borure de magnésium", "MgB2").uncapping("Mg").metal(),
            Molecule.of(Molecule.Kind.MATERIAL, "Siliciure de magnésium", "Mg2Si").boosting(Molecule.Stat.ATOMS, 0.09).crystal(),
            Molecule.of(Molecule.Kind.MATERIAL, "Fluorure de magnésium", "MgF2").boosting(Molecule.Stat.PARTICLES, 0.09).crystal(),
            Molecule.of(Molecule.Kind.MATERIAL, "Niobium-étain", "Nb3Sn").uncapping("Sn").metal(),
            Molecule.of(Molecule.Kind.MATERIAL, "Niobium-titane", "NbTi").boosting(Molecule.Stat.DARK_GROWTH, 0.11).metal(),
            Molecule.of(Molecule.Kind.MATERIAL, "Nitinol", "NiTi").uncapping("Ni").metal(),
            Molecule.of(Molecule.Kind.MATERIAL, "Disiliciure de molybdène", "MoSi2").uncapping("Mo").metal(),
            Molecule.of(Molecule.Kind.MATERIAL, "Trioxyde de tungstène", "WO3").boosting(Molecule.Stat.SPACE, 0.11).crystal(),
            Molecule.of(Molecule.Kind.MATERIAL, "Pentoxyde de vanadium", "V2O5").uncapping("V").crystal(),
            Molecule.of(Molecule.Kind.MATERIAL, "Oxyde de chrome", "Cr2O3").uncapping("Cr").crystal(),
            Molecule.of(Molecule.Kind.MATERIAL, "Zircone", "ZrO2").uncapping("Zr").crystal(),
            Molecule.of(Molecule.Kind.MATERIAL, "Dioxyde d'hafnium", "HfO2").boosting(Molecule.Stat.ATOMS, 0.11).crystal(),
            Molecule.of(Molecule.Kind.MATERIAL, "Oxyde de nickel", "NiO").boosting(Molecule.Stat.PARTICLES, 0.09).crystal(),
            Molecule.of(Molecule.Kind.MATERIAL, "Oxyde de scandium", "Sc2O3").uncapping("Sc").crystal(),
            Molecule.of(Molecule.Kind.MATERIAL, "Oxyde d'yttrium", "Y2O3").uncapping("Y").crystal(),
            Molecule.of(Molecule.Kind.MATERIAL, "Bleu de cobalt", "CoAl2O4").boosting(Molecule.Stat.DARK_GROWTH, 0.11).crystal(),
            Molecule.of(Molecule.Kind.MATERIAL, "Bleu de Prusse", "Fe7(CN)18").uncapping("Fe").crystal(),
            Molecule.of(Molecule.Kind.MATERIAL, "Ferrite de zinc", "ZnFe2O4").boosting(Molecule.Stat.SPACE, 0.13).crystal(),
            Molecule.of(Molecule.Kind.MATERIAL, "Ferrite de baryum", "BaFe12O19").boosting(Molecule.Stat.ATOMS, 0.18).crystal(),
            Molecule.of(Molecule.Kind.MATERIAL, "Ciment", "Ca3SiO5").boosting(Molecule.Stat.PARTICLES, 0.13).crystal(),
            Molecule.of(Molecule.Kind.MATERIAL, "Silicate de sodium", "Na2SiO3").uncapping("Na").solid(),
            Molecule.of(Molecule.Kind.MATERIAL, "Grenat YAG", "Y3Al5O12").boosting(Molecule.Stat.DARK_GROWTH, 0.18).crystal(),
            Molecule.of(Molecule.Kind.MATERIAL, "Supraconducteur YBCO", "YBa2Cu3O7").boosting(Molecule.Stat.SPACE, 0.18).crystal(),
            Molecule.of(Molecule.Kind.MATERIAL, "Oxyde d'argent", "Ag2O").uncapping("Ag").crystal(),
            Molecule.of(Molecule.Kind.MATERIAL, "Oxyde de mercure", "HgO").uncapping("Hg").crystal(),
            Molecule.of(Molecule.Kind.MATERIAL, "Oxyde d'or", "Au2O3").uncapping("Au").crystal(),
            Molecule.of(Molecule.Kind.MATERIAL, "Tétroxyde d'osmium", "OsO4").uncapping("Os").solid(),
            Molecule.of(Molecule.Kind.MATERIAL, "Dioxyde de ruthénium", "RuO2").uncapping("Ru").crystal(),
            Molecule.of(Molecule.Kind.MATERIAL, "Dioxyde d'iridium", "IrO2").uncapping("Ir").crystal(),
            Molecule.of(Molecule.Kind.MATERIAL, "Heptoxyde de rhénium", "Re2O7").uncapping("Re").solid(),
            Molecule.of(Molecule.Kind.MATERIAL, "Hexafluorure de tungstène", "WF6").boosting(Molecule.Stat.ATOMS, 0.13).gas(),
            Molecule.of(Molecule.Kind.MATERIAL, "Hexafluorure de platine", "PtF6").uncapping("Pt").solid(),
            Molecule.of(Molecule.Kind.MATERIAL, "Tétrachlorure de titane", "TiCl4").boosting(Molecule.Stat.PARTICLES, 0.11).liquid(),
            Molecule.of(Molecule.Kind.MATERIAL, "Nickel carbonyle", "Ni(CO)4").boosting(Molecule.Stat.DARK_GROWTH, 0.11).liquid(),
            Molecule.of(Molecule.Kind.MATERIAL, "Fer carbonyle", "Fe(CO)5").boosting(Molecule.Stat.SPACE, 0.11).liquid(),
            Molecule.of(Molecule.Kind.MATERIAL, "Ferrocène", "Fe(C5H5)2").boosting(Molecule.Stat.ATOMS, 0.11).solid(),
            Molecule.of(Molecule.Kind.MATERIAL, "Cisplatine", "Pt(NH3)2Cl2").boosting(Molecule.Stat.PARTICLES, 0.13).solid(),
            Molecule.of(Molecule.Kind.MATERIAL, "Plomb tétraéthyle", "Pb(C2H5)4").boosting(Molecule.Stat.DARK_GROWTH, 0.13).liquid(),
            Molecule.of(Molecule.Kind.MATERIAL, "Diméthylmercure", "Hg(CH3)2").boosting(Molecule.Stat.SPACE, 0.11).liquid(),

            // La chimie du carbone : hydrocarbures, alcools, solvants, plastiques, arômes, médicaments.
            Molecule.of(Molecule.Kind.ORGANIC, "Éthane", "C2H6").boosting(Molecule.Stat.PARTICLES, 0.08).gas(),
            Molecule.of(Molecule.Kind.ORGANIC, "Propane", "C3H8").boosting(Molecule.Stat.SPACE, 0.08).gas(),
            Molecule.of(Molecule.Kind.ORGANIC, "Butane", "C4H10").boosting(Molecule.Stat.PARTICLES, 0.10).gas(),
            Molecule.of(Molecule.Kind.ORGANIC, "Pentane", "C5H12").boosting(Molecule.Stat.ATOMS, 0.10).liquid(),
            Molecule.of(Molecule.Kind.ORGANIC, "Hexane", "C6H14").boosting(Molecule.Stat.DARK_GROWTH, 0.10).liquid(),
            Molecule.of(Molecule.Kind.ORGANIC, "Octane", "C8H18").boosting(Molecule.Stat.PARTICLES, 0.12).liquid(),
            Molecule.of(Molecule.Kind.ORGANIC, "Cyclohexane", "C6H12").boosting(Molecule.Stat.SPACE, 0.10).liquid(),
            Molecule.of(Molecule.Kind.ORGANIC, "Éthylène", "C2H4").boosting(Molecule.Stat.PARTICLES, 0.08).gas(),
            Molecule.of(Molecule.Kind.ORGANIC, "Propylène", "C3H6").boosting(Molecule.Stat.ATOMS, 0.08).gas(),
            Molecule.of(Molecule.Kind.ORGANIC, "Acétylène", "C2H2").boosting(Molecule.Stat.DARK_GROWTH, 0.08).gas(),
            Molecule.of(Molecule.Kind.ORGANIC, "Butadiène", "C4H6").boosting(Molecule.Stat.PARTICLES, 0.10).gas(),
            Molecule.of(Molecule.Kind.ORGANIC, "Isoprène", "C5H8").boosting(Molecule.Stat.SPACE, 0.10).liquid(),
            Molecule.of(Molecule.Kind.ORGANIC, "Benzène", "C6H6").boosting(Molecule.Stat.PARTICLES, 0.10).liquid(),
            Molecule.of(Molecule.Kind.ORGANIC, "Toluène", "C7H8").boosting(Molecule.Stat.ATOMS, 0.10).liquid(),
            Molecule.of(Molecule.Kind.ORGANIC, "Xylène", "C8H10").boosting(Molecule.Stat.DARK_GROWTH, 0.10).liquid(),
            Molecule.of(Molecule.Kind.ORGANIC, "Styrène", "C8H8").boosting(Molecule.Stat.PARTICLES, 0.10).liquid(),
            Molecule.of(Molecule.Kind.ORGANIC, "Naphtalène", "C10H8").boosting(Molecule.Stat.SPACE, 0.12).solid(),
            Molecule.of(Molecule.Kind.ORGANIC, "Anthracène", "C14H10").boosting(Molecule.Stat.PARTICLES, 0.12).solid(),
            Molecule.of(Molecule.Kind.ORGANIC, "Limonène", "C10H16").boosting(Molecule.Stat.ATOMS, 0.12).liquid(),
            Molecule.of(Molecule.Kind.ORGANIC, "Méthanol", "CH3OH").boosting(Molecule.Stat.DARK_GROWTH, 0.08).liquid(),
            Molecule.of(Molecule.Kind.ORGANIC, "Éthanol", "C2H5OH").boosting(Molecule.Stat.PARTICLES, 0.08).liquid(),
            Molecule.of(Molecule.Kind.ORGANIC, "Isopropanol", "C3H7OH").boosting(Molecule.Stat.SPACE, 0.10).liquid(),
            Molecule.of(Molecule.Kind.ORGANIC, "Éthylène glycol", "C2H6O2").boosting(Molecule.Stat.PARTICLES, 0.10).liquid(),
            Molecule.of(Molecule.Kind.ORGANIC, "Glycérol", "C3H8O3").boosting(Molecule.Stat.ATOMS, 0.10).liquid(),
            Molecule.of(Molecule.Kind.ORGANIC, "Phénol", "C6H5OH").boosting(Molecule.Stat.DARK_GROWTH, 0.10).solid(),
            Molecule.of(Molecule.Kind.ORGANIC, "Formaldéhyde", "CH2O").boosting(Molecule.Stat.PARTICLES, 0.08).gas(),
            Molecule.of(Molecule.Kind.ORGANIC, "Acétaldéhyde", "CH3CHO").boosting(Molecule.Stat.SPACE, 0.08).liquid(),
            Molecule.of(Molecule.Kind.ORGANIC, "Acétone", "C3H6O").boosting(Molecule.Stat.PARTICLES, 0.10).liquid(),
            Molecule.of(Molecule.Kind.ORGANIC, "Éther", "C4H10O").boosting(Molecule.Stat.ATOMS, 0.10).liquid(),
            Molecule.of(Molecule.Kind.ORGANIC, "Acétate d'éthyle", "CH3COOC2H5").boosting(Molecule.Stat.DARK_GROWTH, 0.10).liquid(),
            Molecule.of(Molecule.Kind.ORGANIC, "Méthylamine", "CH3NH2").boosting(Molecule.Stat.PARTICLES, 0.08).gas(),
            Molecule.of(Molecule.Kind.ORGANIC, "Aniline", "C6H5NH2").boosting(Molecule.Stat.SPACE, 0.10).liquid(),
            Molecule.of(Molecule.Kind.ORGANIC, "Pyridine", "C5H5N").boosting(Molecule.Stat.PARTICLES, 0.10).liquid(),
            Molecule.of(Molecule.Kind.ORGANIC, "Acétonitrile", "CH3CN").boosting(Molecule.Stat.ATOMS, 0.08).liquid(),
            Molecule.of(Molecule.Kind.ORGANIC, "Acrylonitrile", "C3H3N").boosting(Molecule.Stat.DARK_GROWTH, 0.08).liquid(),
            Molecule.of(Molecule.Kind.ORGANIC, "Urée", "CO(NH2)2").boosting(Molecule.Stat.PARTICLES, 0.10).solid(),
            Molecule.of(Molecule.Kind.ORGANIC, "Mélamine", "C3H6N6").boosting(Molecule.Stat.SPACE, 0.12).solid(),
            Molecule.of(Molecule.Kind.ORGANIC, "Imidazole", "C3H4N2").boosting(Molecule.Stat.PARTICLES, 0.10).solid(),
            Molecule.of(Molecule.Kind.ORGANIC, "Furane", "C4H4O").boosting(Molecule.Stat.ATOMS, 0.10).liquid(),
            Molecule.of(Molecule.Kind.ORGANIC, "Thiophène", "C4H4S").boosting(Molecule.Stat.DARK_GROWTH, 0.10).liquid(),
            Molecule.of(Molecule.Kind.ORGANIC, "Diméthylsulfoxyde", "C2H6OS").boosting(Molecule.Stat.PARTICLES, 0.10).liquid(),
            Molecule.of(Molecule.Kind.ORGANIC, "Chloroforme", "CHCl3").boosting(Molecule.Stat.SPACE, 0.10).liquid(),
            Molecule.of(Molecule.Kind.ORGANIC, "Dichlorométhane", "CH2Cl2").boosting(Molecule.Stat.PARTICLES, 0.10).liquid(),
            Molecule.of(Molecule.Kind.ORGANIC, "Tétrachlorure de carbone", "CCl4").boosting(Molecule.Stat.ATOMS, 0.12).liquid(),
            Molecule.of(Molecule.Kind.ORGANIC, "Fréon", "CCl2F2").boosting(Molecule.Stat.DARK_GROWTH, 0.10).gas(),
            Molecule.of(Molecule.Kind.ORGANIC, "Tétrafluoroéthylène", "C2F4").boosting(Molecule.Stat.PARTICLES, 0.10).gas(),
            Molecule.of(Molecule.Kind.ORGANIC, "Chlorure de vinyle", "C2H3Cl").boosting(Molecule.Stat.SPACE, 0.10).gas(),
            Molecule.of(Molecule.Kind.ORGANIC, "Caprolactame", "C6H11NO").boosting(Molecule.Stat.PARTICLES, 0.12).solid(),
            Molecule.of(Molecule.Kind.ORGANIC, "Méthacrylate de méthyle", "C5H8O2").boosting(Molecule.Stat.ATOMS, 0.10).liquid(),
            Molecule.of(Molecule.Kind.ORGANIC, "Bisphénol A", "C15H16O2").boosting(Molecule.Stat.DARK_GROWTH, 0.14).solid(),
            Molecule.of(Molecule.Kind.ORGANIC, "Menthol", "C10H20O").boosting(Molecule.Stat.PARTICLES, 0.12).solid(),
            Molecule.of(Molecule.Kind.ORGANIC, "Camphre", "C10H16O").boosting(Molecule.Stat.SPACE, 0.12).solid(),
            Molecule.of(Molecule.Kind.ORGANIC, "Vanilline", "C8H8O3").boosting(Molecule.Stat.PARTICLES, 0.12).solid(),
            Molecule.of(Molecule.Kind.ORGANIC, "Indigo", "C16H10N2O2").boosting(Molecule.Stat.ATOMS, 0.14).solid(),
            Molecule.of(Molecule.Kind.ORGANIC, "Saccharine", "C7H5NO3S").boosting(Molecule.Stat.DARK_GROWTH, 0.12).solid(),
            Molecule.of(Molecule.Kind.ORGANIC, "Aspirine", "C9H8O4").boosting(Molecule.Stat.PARTICLES, 0.12).solid(),
            Molecule.of(Molecule.Kind.ORGANIC, "Paracétamol", "C8H9NO2").boosting(Molecule.Stat.SPACE, 0.12).solid(),
            Molecule.of(Molecule.Kind.ORGANIC, "Ibuprofène", "C13H18O2").boosting(Molecule.Stat.PARTICLES, 0.14).solid(),
            Molecule.of(Molecule.Kind.ORGANIC, "Caféine", "C8H10N4O2").boosting(Molecule.Stat.ATOMS, 0.14).solid(),
            Molecule.of(Molecule.Kind.ORGANIC, "Théobromine", "C7H8N4O2").boosting(Molecule.Stat.DARK_GROWTH, 0.12).solid(),
            Molecule.of(Molecule.Kind.ORGANIC, "Nicotine", "C10H14N2").boosting(Molecule.Stat.PARTICLES, 0.12).liquid(),
            Molecule.of(Molecule.Kind.ORGANIC, "Trinitrotoluène", "C7H5N3O6").boosting(Molecule.Stat.SPACE, 0.14).solid(),
            Molecule.of(Molecule.Kind.ORGANIC, "Nitroglycérine", "C3H5N3O9").boosting(Molecule.Stat.PARTICLES, 0.14).liquid(),

            // Les molécules du vivant : sucres, acides aminés, bases de l'ADN, vitamines, messagers, remèdes tirés des plantes.
            Molecule.of(Molecule.Kind.LIFE, "Glucose", "C6H12O6").boosting(Molecule.Stat.DARK_GROWTH, 0.13).solid(),
            Molecule.of(Molecule.Kind.LIFE, "Saccharose", "C12H22O11").boosting(Molecule.Stat.PARTICLES, 0.17).solid(),
            Molecule.of(Molecule.Kind.LIFE, "Ribose", "C5H10O5").boosting(Molecule.Stat.SPACE, 0.13).solid(),
            Molecule.of(Molecule.Kind.LIFE, "Désoxyribose", "C5H10O4").boosting(Molecule.Stat.ATOMS, 0.13).solid(),
            Molecule.of(Molecule.Kind.LIFE, "Acide pyruvique", "C3H4O3").boosting(Molecule.Stat.DARK_GROWTH, 0.11).liquid(),
            Molecule.of(Molecule.Kind.LIFE, "Acide butyrique", "C4H8O2").boosting(Molecule.Stat.PARTICLES, 0.11).liquid(),
            Molecule.of(Molecule.Kind.LIFE, "Acide caprylique", "C8H16O2").boosting(Molecule.Stat.SPACE, 0.13).liquid(),
            Molecule.of(Molecule.Kind.LIFE, "Glycine", "C2H5NO2").boosting(Molecule.Stat.ATOMS, 0.11).solid(),
            Molecule.of(Molecule.Kind.LIFE, "Alanine", "C3H7NO2").boosting(Molecule.Stat.DARK_GROWTH, 0.11).solid(),
            Molecule.of(Molecule.Kind.LIFE, "Sérine", "C3H7NO3").boosting(Molecule.Stat.PARTICLES, 0.11).solid(),
            Molecule.of(Molecule.Kind.LIFE, "Cystéine", "C3H7NO2S").boosting(Molecule.Stat.SPACE, 0.13).solid(),
            Molecule.of(Molecule.Kind.LIFE, "Proline", "C5H9NO2").boosting(Molecule.Stat.ATOMS, 0.13).solid(),
            Molecule.of(Molecule.Kind.LIFE, "Valine", "C5H11NO2").boosting(Molecule.Stat.DARK_GROWTH, 0.13).solid(),
            Molecule.of(Molecule.Kind.LIFE, "Leucine", "C6H13NO2").boosting(Molecule.Stat.PARTICLES, 0.13).solid(),
            Molecule.of(Molecule.Kind.LIFE, "Méthionine", "C5H11NO2S").boosting(Molecule.Stat.SPACE, 0.13).solid(),
            Molecule.of(Molecule.Kind.LIFE, "Acide aspartique", "C4H7NO4").boosting(Molecule.Stat.ATOMS, 0.13).solid(),
            Molecule.of(Molecule.Kind.LIFE, "Acide glutamique", "C5H9NO4").boosting(Molecule.Stat.DARK_GROWTH, 0.13).solid(),
            Molecule.of(Molecule.Kind.LIFE, "Lysine", "C6H14N2O2").boosting(Molecule.Stat.PARTICLES, 0.13).solid(),
            Molecule.of(Molecule.Kind.LIFE, "Histidine", "C6H9N3O2").boosting(Molecule.Stat.SPACE, 0.13).solid(),
            Molecule.of(Molecule.Kind.LIFE, "Phénylalanine", "C9H11NO2").boosting(Molecule.Stat.ATOMS, 0.13).solid(),
            Molecule.of(Molecule.Kind.LIFE, "Tyrosine", "C9H11NO3").boosting(Molecule.Stat.DARK_GROWTH, 0.13).solid(),
            Molecule.of(Molecule.Kind.LIFE, "Tryptophane", "C11H12N2O2").boosting(Molecule.Stat.PARTICLES, 0.15).solid(),
            Molecule.of(Molecule.Kind.LIFE, "Adénine", "C5H5N5").boosting(Molecule.Stat.SPACE, 0.13).solid(),
            Molecule.of(Molecule.Kind.LIFE, "Guanine", "C5H5N5O").boosting(Molecule.Stat.ATOMS, 0.13).solid(),
            Molecule.of(Molecule.Kind.LIFE, "Cytosine", "C4H5N3O").boosting(Molecule.Stat.DARK_GROWTH, 0.11).solid(),
            Molecule.of(Molecule.Kind.LIFE, "Thymine", "C5H6N2O2").boosting(Molecule.Stat.PARTICLES, 0.13).solid(),
            Molecule.of(Molecule.Kind.LIFE, "Uracile", "C4H4N2O2").boosting(Molecule.Stat.SPACE, 0.11).solid(),
            Molecule.of(Molecule.Kind.LIFE, "ATP", "C10H16N5O13P3").boosting(Molecule.Stat.ATOMS, 0.20).solid(),
            Molecule.of(Molecule.Kind.LIFE, "Vitamine C", "C6H8O6").boosting(Molecule.Stat.DARK_GROWTH, 0.13).solid(),
            Molecule.of(Molecule.Kind.LIFE, "Vitamine B3", "C6H5NO2").boosting(Molecule.Stat.PARTICLES, 0.13).solid(),
            Molecule.of(Molecule.Kind.LIFE, "Vitamine B6", "C8H11NO3").boosting(Molecule.Stat.SPACE, 0.13).solid(),
            Molecule.of(Molecule.Kind.LIFE, "Biotine", "C10H16N2O3S").boosting(Molecule.Stat.ATOMS, 0.15).solid(),
            Molecule.of(Molecule.Kind.LIFE, "Créatine", "C4H9N3O2").boosting(Molecule.Stat.DARK_GROWTH, 0.13).solid(),
            Molecule.of(Molecule.Kind.LIFE, "Taurine", "C2H7NO3S").boosting(Molecule.Stat.PARTICLES, 0.13).solid(),
            Molecule.of(Molecule.Kind.LIFE, "Glutathion", "C10H17N3O6S").boosting(Molecule.Stat.SPACE, 0.17).solid(),
            Molecule.of(Molecule.Kind.LIFE, "Acide urique", "C5H4N4O3").boosting(Molecule.Stat.ATOMS, 0.13).solid(),
            Molecule.of(Molecule.Kind.LIFE, "Histamine", "C5H9N3").boosting(Molecule.Stat.DARK_GROWTH, 0.13).solid(),
            Molecule.of(Molecule.Kind.LIFE, "Dopamine", "C8H11NO2").boosting(Molecule.Stat.PARTICLES, 0.13).solid(),
            Molecule.of(Molecule.Kind.LIFE, "Adrénaline", "C9H13NO3").boosting(Molecule.Stat.SPACE, 0.13).solid(),
            Molecule.of(Molecule.Kind.LIFE, "Sérotonine", "C10H12N2O").boosting(Molecule.Stat.ATOMS, 0.13).solid(),
            Molecule.of(Molecule.Kind.LIFE, "Mélatonine", "C13H16N2O2").boosting(Molecule.Stat.DARK_GROWTH, 0.15).solid(),
            Molecule.of(Molecule.Kind.LIFE, "Pénicilline", "C16H18N2O4S").boosting(Molecule.Stat.PARTICLES, 0.17).solid(),
            Molecule.of(Molecule.Kind.LIFE, "Morphine", "C17H19NO3").boosting(Molecule.Stat.SPACE, 0.15).solid(),
            Molecule.of(Molecule.Kind.LIFE, "Quinine", "C20H24N2O2").boosting(Molecule.Stat.ATOMS, 0.17).solid(),
            Molecule.of(Molecule.Kind.LIFE, "Resvératrol", "C14H12O3").boosting(Molecule.Stat.DARK_GROWTH, 0.15).solid(),
            Molecule.of(Molecule.Kind.LIFE, "Curcumine", "C21H20O6").boosting(Molecule.Stat.PARTICLES, 0.17).solid(),

            // Les lanthanides, de 57 à 71, puis les éléments radioactifs et les superlourds dont on connaît un composé.
            Molecule.of(Molecule.Kind.RARE, "Oxyde de lanthane", "La2O3").uncapping("La").crystal(),
            Molecule.of(Molecule.Kind.RARE, "Fluorure de lanthane", "LaF3").boosting(Molecule.Stat.DARK_GROWTH, 0.14).crystal(),
            Molecule.of(Molecule.Kind.RARE, "Hexaborure de lanthane", "LaB6").uncapping("B").metal(),
            Molecule.of(Molecule.Kind.RARE, "Oxyde de cérium", "CeO2").uncapping("Ce").crystal(),
            Molecule.of(Molecule.Kind.RARE, "Fluorure de cérium", "CeF3").boosting(Molecule.Stat.SPACE, 0.14).crystal(),
            Molecule.of(Molecule.Kind.RARE, "Monazite", "CePO4").boosting(Molecule.Stat.DARK_GROWTH, 0.16).crystal(),
            Molecule.of(Molecule.Kind.RARE, "Bastnäsite", "CeCO3F").boosting(Molecule.Stat.SPACE, 0.14).crystal(),
            Molecule.of(Molecule.Kind.RARE, "Oxyde de praséodyme", "Pr6O11").uncapping("Pr").crystal(),
            Molecule.of(Molecule.Kind.RARE, "Oxyde de néodyme", "Nd2O3").uncapping("Nd").crystal(),
            Molecule.of(Molecule.Kind.RARE, "Aimant au néodyme", "Nd2Fe14B").uncapping("Fe").metal(),
            Molecule.of(Molecule.Kind.RARE, "Oxyde de prométhium", "Pm2O3").uncapping("Pm").crystal(),
            Molecule.of(Molecule.Kind.RARE, "Oxyde de samarium", "Sm2O3").uncapping("Sm").crystal(),
            Molecule.of(Molecule.Kind.RARE, "Aimant samarium-cobalt", "SmCo5").uncapping("Co").metal(),
            Molecule.of(Molecule.Kind.RARE, "Oxyde d'europium", "Eu2O3").uncapping("Eu").crystal(),
            Molecule.of(Molecule.Kind.RARE, "Sulfure d'europium", "EuS").boosting(Molecule.Stat.DARK_GROWTH, 0.14).crystal(),
            Molecule.of(Molecule.Kind.RARE, "Oxyde de gadolinium", "Gd2O3").uncapping("Gd").crystal(),
            Molecule.of(Molecule.Kind.RARE, "Grenat GGG", "Gd3Ga5O12").uncapping("Ga").crystal(),
            Molecule.of(Molecule.Kind.RARE, "Oxyde de terbium", "Tb4O7").uncapping("Tb").crystal(),
            Molecule.of(Molecule.Kind.RARE, "Oxyde de dysprosium", "Dy2O3").uncapping("Dy").crystal(),
            Molecule.of(Molecule.Kind.RARE, "Oxyde d'holmium", "Ho2O3").uncapping("Ho").crystal(),
            Molecule.of(Molecule.Kind.RARE, "Oxyde d'erbium", "Er2O3").uncapping("Er").crystal(),
            Molecule.of(Molecule.Kind.RARE, "Oxyde de thulium", "Tm2O3").uncapping("Tm").crystal(),
            Molecule.of(Molecule.Kind.RARE, "Oxyde d'ytterbium", "Yb2O3").uncapping("Yb").crystal(),
            Molecule.of(Molecule.Kind.RARE, "Oxyde de lutécium", "Lu2O3").uncapping("Lu").crystal(),
            Molecule.of(Molecule.Kind.RARE, "Silicate de lutécium", "Lu2SiO5").uncapping("Si").crystal(),
            Molecule.of(Molecule.Kind.RARE, "Pertechnétate de sodium", "NaTcO4").uncapping("Tc").crystal(),
            Molecule.of(Molecule.Kind.RARE, "Chlorure de radium", "RaCl2").uncapping("Ra").crystal(),
            Molecule.of(Molecule.Kind.RARE, "Dioxyde de polonium", "PoO2").uncapping("Po").crystal(),
            Molecule.of(Molecule.Kind.RARE, "Hydrure de polonium", "PoH2").boosting(Molecule.Stat.SPACE, 0.14).liquid(),
            Molecule.of(Molecule.Kind.RARE, "Astature d'hydrogène", "HAt").boosting(Molecule.Stat.DARK_GROWTH, 0.14).gas(),
            Molecule.of(Molecule.Kind.RARE, "Tétrachlorure de rutherfordium", "RfCl4").uncapping("Rf").solid(),
            Molecule.of(Molecule.Kind.RARE, "Pentachlorure de dubnium", "DbCl5").uncapping("Db").solid(),
            Molecule.of(Molecule.Kind.RARE, "Oxychlorure de seaborgium", "SgO2Cl2").uncapping("Sg").solid(),
            Molecule.of(Molecule.Kind.RARE, "Oxychlorure de bohrium", "BhO3Cl").uncapping("Bh").liquid(),
            Molecule.of(Molecule.Kind.RARE, "Tétroxyde de hassium", "HsO4").uncapping("Hs").solid(),
            Molecule.of(Molecule.Kind.RARE, "Hydroxyde de nihonium", "NhOH").uncapping("Nh").crystal());

    private Molecules() {}
}
